version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: kanban-database
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

  # supertest:
  #   image: postgres:latest
  #   container_name: test-database
  #   hostname: supertest
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=test
  #     - POSTGRES_PASSWORD=test123
  #     - POSTGRES_DB=supertest
  #   ports:
  #     - 2345:5432

  server:
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kanban-server
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - postgres
      - supertest
    volumes:
      - ./:/usr/app

volumes:
  pgdata:
    driver: local
