version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: kanban-database
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

  server:
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kanban-server
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/app

volumes:
  pgdata:
    driver: local
